CREATE TABLE USER (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	lastname VARCHAR(32) NOT NULL,
	firstname VARCHAR(32) NOT NULL,
	username VARCHAR(32) NOT NULL,
	password VARCHAR(32) NOT NULL,
	mail VARCHAR(50) NOT NULL
);

CREATE TABLE EVENT (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(32) NOT NULL,
	owner INT(6) NOT NULL,
	guests INT(6) NULL,
	date_created DATETIME() NOT NULL,
	date_event DATETIME() NOT NULL,
	description VARCHAR(50) NULL
);

ALTER TABLE EVENT ADD FOREIGN KEY (owner) REFERENCES USER(id);