CREATE TABLE USER (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	lastname VARCHAR(32) NOT NULL,
	firstname VARCHAR(32) NOT NULL,
	username VARCHAR(32) NOT NULL UNIQUE,
	password VARCHAR(32) NOT NULL,
	mail VARCHAR(50) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE EVENT ( 
	id INT(4) NOT NULL AUTO_INCREMENT,
	name VARCHAR(32) NOT NULL,
	owner INT(4) NOT NULL,
	guests VARCHAR(300) NULL,
	date_created DATETIME NOT NULL,
	date_event DATETIME NOT NULL,
	description VARCHAR(150) NULL,
	PRIMARY KEY (id)
) ENGINE = InnoDB;